import Foundation
import SwiftData

/// How the total was divided between the people involved.
///
/// Whichever method is chosen, the persisted `ExpenseShare.amountMinorUnits`
/// values are the source of truth and always sum to the expense total. The
/// method and the per-person `weight` are kept so the editor can reopen with
/// the original intent ("40% each") rather than the resolved cents.
enum SplitMethod: String, CaseIterable, Codable, Identifiable, Sendable {
    /// Split evenly between everyone selected.
    case equal
    /// Each person's share typed in directly.
    case exact
    /// Percentages that must total 100.
    case percent
    /// Relative shares — "Ana counts double".
    case shares
    /// Even split, then a per-person plus or minus adjustment.
    case adjustment
    /// Derived from line items on the receipt.
    case itemized

    var id: String { rawValue }

    var title: String {
        switch self {
        case .equal: String(localized: "Equally")
        case .exact: String(localized: "Exact amounts")
        case .percent: String(localized: "Percentages")
        case .shares: String(localized: "Shares")
        case .adjustment: String(localized: "Plus/minus")
        case .itemized: String(localized: "By item")
        }
    }

    var shortTitle: String {
        switch self {
        case .equal: String(localized: "Equal")
        case .exact: String(localized: "Exact")
        case .percent: String(localized: "%")
        case .shares: String(localized: "Shares")
        case .adjustment: String(localized: "+/−")
        case .itemized: String(localized: "Items")
        }
    }

    var symbol: String {
        switch self {
        case .equal: "equal"
        case .exact: "textformat.123"
        case .percent: "percent"
        case .shares: "chart.pie.fill"
        case .adjustment: "plusminus"
        case .itemized: "list.bullet.rectangle"
        }
    }

    var explanation: String {
        switch self {
        case .equal: String(localized: "Everyone selected pays the same amount.")
        case .exact: String(localized: "Type what each person owes. Must add up to the total.")
        case .percent: String(localized: "Give each person a percentage. Must add up to 100%.")
        case .shares: String(localized: "Give each person a number of shares. Someone with 2 shares pays twice as much as someone with 1.")
        case .adjustment: String(localized: "Split evenly, then add or subtract for individual extras.")
        case .itemized: String(localized: "Assign each line on the receipt to the people who had it.")
        }
    }
}

/// A shared cost. Also used for a one-off debt between two people (no group).
@Model
final class Expense {
    var id: UUID = UUID()
    var title: String = ""
    var notes: String = ""
    /// The total, in `currencyCode` minor units. Always equals the sum of shares.
    var amountMinorUnits: Int = 0
    var currencyCode: String = "USD"
    var date: Date = Date()
    var createdAt: Date = Date()
    var updatedAt: Date = Date()

    /// A fingerprint of this row's contents as the server last saw them.
    ///
    /// Sync decides what to push by comparing it against the row's current
    /// fingerprint. A hash is used rather than a dirty flag or a timestamp
    /// because both of those have to be *remembered* at every write site, and
    /// one forgotten line means an edit that silently never syncs. A hash cannot
    /// be forgotten: if the contents differ, it differs.
    var syncedFingerprint: String = ""
    var categoryRaw: String = ExpenseCategory.general.rawValue
    var splitMethodRaw: String = SplitMethod.equal.rawValue

    /// Rate to the user's base currency at the time of entry, so historical
    /// totals don't silently move when exchange rates do. 1.0 when already base.
    var exchangeRateToBase: Double = 1.0
    var baseCurrencyCode: String = "USD"

    /// Tax and tip broken out of the total, when itemizing.
    var taxMinorUnits: Int = 0
    var tipMinorUnits: Int = 0

    @Attribute(.externalStorage) var receiptImageData: Data?
    /// Raw OCR text from a scanned receipt, kept so search can match on it.
    var receiptText: String = ""

    var group: SpendingGroup?
    /// Set when this expense was generated by a recurring rule.
    var generatedByRuleID: UUID?

    @Relationship(deleteRule: .cascade, inverse: \ExpensePayer.expense)
    var payers: [ExpensePayer]? = []

    @Relationship(deleteRule: .cascade, inverse: \ExpenseShare.expense)
    var shares: [ExpenseShare]? = []

    @Relationship(deleteRule: .cascade, inverse: \ExpenseLineItem.expense)
    var lineItems: [ExpenseLineItem]? = []

    @Relationship(deleteRule: .cascade, inverse: \ExpenseComment.expense)
    var comments: [ExpenseComment]? = []

    init(
        title: String = "",
        amountMinorUnits: Int = 0,
        currencyCode: String = "USD",
        date: Date = Date(),
        category: ExpenseCategory = .general,
        splitMethod: SplitMethod = .equal,
        group: SpendingGroup? = nil
    ) {
        self.id = UUID()
        self.title = title
        self.amountMinorUnits = amountMinorUnits
        self.currencyCode = currencyCode
        self.baseCurrencyCode = currencyCode
        self.date = date
        self.createdAt = Date()
        self.updatedAt = Date()
        self.categoryRaw = category.rawValue
        self.splitMethodRaw = splitMethod.rawValue
        self.group = group
    }
}

extension Expense {
    var category: ExpenseCategory {
        get { ExpenseCategory(rawValue: categoryRaw) ?? .general }
        set { categoryRaw = newValue.rawValue }
    }

    var splitMethod: SplitMethod {
        get { SplitMethod(rawValue: splitMethodRaw) ?? .equal }
        set { splitMethodRaw = newValue.rawValue }
    }

    var total: Money { Money(minorUnits: amountMinorUnits, currencyCode: currencyCode) }

    var payerList: [ExpensePayer] { payers ?? [] }
    var shareList: [ExpenseShare] { shares ?? [] }
    var lineItemList: [ExpenseLineItem] { (lineItems ?? []).sorted { $0.sortOrder < $1.sortOrder } }
    var commentList: [ExpenseComment] { (comments ?? []).sorted { $0.createdAt < $1.createdAt } }

    var displayTitle: String {
        title.isEmpty ? String(localized: "Untitled expense") : title
    }

    /// People who put money in, with how much each contributed.
    var payingParticipants: [Participant] {
        payerList.compactMap(\.participant)
    }

    /// People who owe a non-zero share.
    var owingParticipants: [Participant] {
        shareList.filter { $0.amountMinorUnits != 0 }.compactMap(\.participant)
    }

    /// Everyone touched by this expense, deduplicated.
    var involvedParticipants: [Participant] {
        var seen = Set<UUID>()
        var result: [Participant] = []
        for person in payingParticipants + owingParticipants where seen.insert(person.id).inserted {
            result.append(person)
        }
        return result
    }

    func amountPaid(by participant: Participant) -> Int {
        payerList.filter { $0.participant?.id == participant.id }
            .reduce(0) { $0 + $1.amountMinorUnits }
    }

    func amountOwed(by participant: Participant) -> Int {
        shareList.filter { $0.participant?.id == participant.id }
            .reduce(0) { $0 + $1.amountMinorUnits }
    }

    /// Positive when this person is up on the expense (paid more than their share).
    func net(for participant: Participant) -> Int {
        amountPaid(by: participant) - amountOwed(by: participant)
    }

    /// Equivalent value in the user's base currency, using the rate captured at entry.
    var amountInBaseMinorUnits: Int {
        guard currencyCode != baseCurrencyCode else { return amountMinorUnits }
        let fromDigits = Currency.fractionDigits(for: currencyCode)
        let toDigits = Currency.fractionDigits(for: baseCurrencyCode)
        let major = Double(amountMinorUnits) / pow(10, Double(fromDigits))
        return Int((major * exchangeRateToBase * pow(10, Double(toDigits))).rounded())
    }

    /// One-line summary: "Ana paid $48.00" or "You and 1 other paid $48.00".
    var payerSummary: String {
        let payers = payerList.filter { $0.amountMinorUnits > 0 }
        guard let first = payers.first, let firstPerson = first.participant else {
            return String(localized: "No one paid yet")
        }
        if payers.count == 1 {
            return String(
                format: String(localized: "%@ paid %@", comment: "Person name, amount"),
                firstPerson.displayName,
                total.formatted()
            )
        }
        return String(
            format: String(localized: "%1$@ and %2$lld others paid %3$@", comment: "Person, count, amount"),
            firstPerson.displayName,
            payers.count - 1,
            total.formatted()
        )
    }

    var searchHaystack: String {
        var parts = [title, notes, category.title, receiptText]
        parts.append(contentsOf: lineItemList.map(\.name))
        parts.append(group?.name ?? "")
        parts.append(contentsOf: involvedParticipants.map(\.fullName))
        return parts.joined(separator: " ").lowercased()
    }
}

/// One person's contribution toward paying an expense. Splitwise allows several
/// people to chip in on the same bill, so this is a list rather than one field.
@Model
final class ExpensePayer {
    var id: UUID = UUID()
    var amountMinorUnits: Int = 0
    var participant: Participant?
    var expense: Expense?

    init(participant: Participant?, amountMinorUnits: Int) {
        self.id = UUID()
        self.participant = participant
        self.amountMinorUnits = amountMinorUnits
    }
}

/// What one person owes on an expense.
@Model
final class ExpenseShare {
    var id: UUID = UUID()
    /// Resolved amount owed, in the expense's currency. Source of truth.
    var amountMinorUnits: Int = 0
    /// The input that produced the amount: a percentage, a share count, or a
    /// plus/minus adjustment in minor units, depending on the split method.
    var weight: Double = 0
    var participant: Participant?
    var expense: Expense?

    init(participant: Participant?, amountMinorUnits: Int = 0, weight: Double = 0) {
        self.id = UUID()
        self.participant = participant
        self.amountMinorUnits = amountMinorUnits
        self.weight = weight
    }
}

/// A single line on a receipt, assigned to the people who ordered it.
@Model
final class ExpenseLineItem {
    var id: UUID = UUID()
    var name: String = ""
    var amountMinorUnits: Int = 0
    var quantity: Int = 1
    var sortOrder: Int = 0
    /// Empty means "shared by everyone on the expense".
    var assignees: [Participant]? = []
    var expense: Expense?

    init(name: String, amountMinorUnits: Int, quantity: Int = 1, sortOrder: Int = 0, assignees: [Participant] = []) {
        self.id = UUID()
        self.name = name
        self.amountMinorUnits = amountMinorUnits
        self.quantity = quantity
        self.sortOrder = sortOrder
        self.assignees = assignees
    }

    var assigneeList: [Participant] { assignees ?? [] }
    var lineTotalMinorUnits: Int { amountMinorUnits * max(1, quantity) }
}

/// A note left on an expense.
@Model
final class ExpenseComment {
    var id: UUID = UUID()
    var text: String = ""
    var createdAt: Date = Date()
    var author: Participant?
    var expense: Expense?

    init(text: String, author: Participant?) {
        self.id = UUID()
        self.text = text
        self.author = author
        self.createdAt = Date()
    }
}
